name: scivision
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - scipy
  - pandas
  - fsspec
  - pyyaml
  - requests
  - aiohttp
  - intake
  - intake-xarray
  - pytorch
  - torchvision
  - pip:
      - rasterio
      - pycurl
      - tqdm
      - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git