name: Build frontend
on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
    	uses: actions/setup-node@v1
    	with:
        node-version: '16.15.1'

    - name: Install node packages
      run: npm ci

    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: frontend/build
        message: Deploy to gh-pages
        clean: true

